<a href="https://colab.research.google.com/github/BidexTech/HDSCFall23/blob/main/NumPYArray_and_Pandasdf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

arr = [6, 7, 8, 9]
print(type(arr))

<class 'list'>


In [8]:
a = np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [9]:
print(a.shape) #a is a 1 dimension array with 4 items

(4,)


In [10]:
print(a.dtype)

int64


In [11]:
print(a.ndim)

1


In [12]:
b= np.array([[1,2,3],[4,5,6]])
print(b)
print(b.ndim)
b.shape # b is a 2d array with 2 rows and 3 columns

[[1 2 3]
 [4 5 6]]
2


(2, 3)

In [13]:
b[0,0],b[0,1], b[0,2]
b[1,0], b[1,1], b[1,2]

(4, 5, 6)

In [14]:
np.random.random((2,3)) # a 2x3 array with random values

array([[0.07141988, 0.08505331, 0.81434616],
       [0.64131569, 0.42552316, 0.73987938]])

In [15]:
np.zeros((2,3)) # a 2X3 array of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((2,3)) # array of ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.identity(3) # a 3X3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
#intra-operability of arrays and scalers
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0,3.0]])
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])

print(c + d)

print(c * d)

[[13. 13. 13.]
 [10. 10. 10.]]
[[36. 40. 42.]
 [ 9. 16. 21.]]


In [19]:
print(5 / d)
c **2

[[1.25       1.         0.83333333]
 [0.55555556 0.625      0.71428571]]


array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

In [32]:
a[0], a[3], b[0, 0]

(6, 9, 1)

In [39]:
d[1, 0:2]
e = np.array([[10, 11, 12],[13, 14, 15],[16, 17, 18],[19, 20, 21]])
print(e)
e.shape

#slicing
e[:3, :2]

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


array([[10, 11],
       [13, 14],
       [16, 17]])

In [41]:
#integer indexing
e[[2, 0, 3, 1],[2, 1, 0, 2]]



array([18, 11, 19, 15])

In [42]:
e[e>15]

array([16, 17, 18, 19, 20, 21])

##pandas data frame

In [44]:
import pandas as pd
days = pd.Series(['Monday', 'Tuesday', 'Wednesday',])
print(days)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [45]:
days = pd.Series(['Monday', 'Tuesday', 'Wednesday'],
                 index = ['a', 'b', 'c'])
days

a       Monday
b      Tuesday
c    Wednesday
dtype: object

In [46]:
#creating series from a dictionary
days1 = pd.Series({'a':'Monday', 'b':'Tuesday', 'c':'Wednesday'})
days1

a       Monday
b      Tuesday
c    Wednesday
dtype: object

In [47]:
days[0]


'Monday'

In [48]:
days[1: ]

b      Tuesday
c    Wednesday
dtype: object

In [49]:
days['b']

'Tuesday'

In [50]:
print(pd.DataFrame()) #print an empy dataframe

Empty DataFrame
Columns: []
Index: []


In [51]:
# Create a dataframe from a dictionary
df_dict ={'Country': ['Ghana', 'Kenya', 'Nigeria', 'Togo'],
         'Capital': ['Accra', 'Nairobi', 'Abuja', 'Lome'],
         'Population': [10000, 8500, 35000, 12000],
         'Age': [60, 70, 80, 75]
         }
df = pd.DataFrame(df_dict, index=[2, 4, 6, 8])
df

Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   75

In [65]:
df.iloc[3] #select the row in the at index 3

Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   75

In [53]:
df_list = [['Ghana', 'Accra', 10000, 60],
           ['kenya', 'Nairobi', 8500, 70],
           ['Nigeria', 'Abuja', 35000, 80],
            ['Togo', 'Lome', 12000, 75]]
df1 = pd.DataFrame(df_list, columns=['Country', 'Capital', 'Population', 'Age'],
                   index = [2, 4, 6, 8])
df1

Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   75

In [54]:
df.loc[6] #select row with index label 6

Country       Nigeria
Capital         Abuja
Population      35000
Age                80
Name: 6, dtype: object

In [55]:
df['Capital']

2      Accra
4    Nairobi
6      Abuja
8       Lome
Name: Capital, dtype: object

In [56]:
df.at[6, 'Country']

'Nigeria'

In [57]:
df.iat[2, 0]

'Nigeria'

In [58]:
df

Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   75

In [59]:
df['Population'].sum()

65500

In [60]:
df.mean()

<ipython-input-60-c61f0c8f89b5>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()


Population    16375.00
Age              71.25
dtype: float64

In [61]:
df.describe()

Population        Age
count      4.000000   4.000000
mean   16375.000000  71.250000
std    12499.166639   8.539126
min     8500.000000  60.000000
25%     9625.000000  67.500000
50%    11000.000000  72.500000
75%    17750.000000  76.250000
max    35000.000000  80.000000

In [62]:
#treating Null values
df_dict2 = {'Name': ['James', 'Yemen', 'Caro', np.nan],
            'Pofession': ['Researcher', 'Artist', 'Doctor', 'Writer'],
            'Experience': [12, np.nan, 10, 8],
            'Height': [np.nan, 175, 180, 150]}
new_df = pd.DataFrame(df_dict2)
new_df

Name   Pofession  Experience  Height
0  James  Researcher        12.0     NaN
1  Yemen      Artist         NaN   175.0
2   Caro      Doctor        10.0   180.0
3    NaN      Writer         8.0   150.0

In [63]:
new_df.isnull() #check for cell with missing value as True

Name  Pofession  Experience  Height
0  False      False       False    True
1  False      False        True   False
2  False      False       False   False
3   True      False       False   False

In [64]:
new_df.dropna() #remove role with missing values

Name Pofession  Experience  Height
2  Caro    Doctor        10.0   180.0